apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name:  s-101
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/aml-innov-bpid-810834/gcsjob"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/dbBasic3.py
  sparkVersion: "3.0.0"
  hadoopConf:
    fs.gs.impl: com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
    fs.gs.project.id: aml-innov-bpid-810834
    fs.gs.system.bucket: ravinuodb-bucket
    google.cloud.auth.service.account.enable: "true"
    google.cloud.auth.service.account.json.keyfile: /opt/spark/examples/src/main/python/infra-build.json
  restartPolicy:
    type: OnFailure
    onFailureRetries: 0
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    serviceAccount: spark
    labels:
      version: 3.0.0
